In [3]:
import pandas as pd
PEAK_FILE = '/ihme/covid-19/deaths/mobility_inputs/2020_04_20/peak_locs_april20_.csv'
peaked_df = pd.read_csv(PEAK_FILE)

In [ ]:
df=df[['location_id', 'intercept', 'Days', 'pseudo', 'ln(age-standardized death rate)', COVARIATE]],
            model_location=f'_{args.model_location_id}',
            location_cov=location_cov,
            n_draws=args.n_draws,
            peaked_groups=peaked_df.loc[peaked_df['location_id'].isin(df['location_id'].unique().tolist()), 'location_id'].to_list(),
            exclude_groups=peaked_df.loc[peaked_df['location_id'] == '_60412', 'location_id'].unique().tolist(),

In [4]:
peaked_df

,location,location_id,peak day,peak_date
0,Campania - Italy,35509.0,20.329443,4/2/2020
1,Castile and Leon - Spain,60367.0,21.137209,4/4/2020
2,Castilla-La Mancha - Spain,60360.0,23.081512,4/5/2020
3,Catalonia - Spain,60368.0,25.015163,4/4/2020
4,Community of Madrid - Spain,60361.0,26.895761,4/2/2020
5,Emilia-Romagna - Italy,35502.0,33.783290,4/2/2020
6,King and Snohomish Counties (excluding Life Ca...,60405.0,37.545419,4/10/2020
7,Lazio - Italy,35506.0,25.397161,4/2/2020
8,Liguria - Italy,35496.0,30.562541,4/5/2020
9,Lombardia - Italy,35497.0,37.454435,3/31/2020
10,Marche - Italy,35505.0,29.053541,4/1/2020
11,Valencian Community - Spain,60371.0,22.124670,4/5/2020
12,Valle d'Aosta - Italy,35495.0,16.043788,4/2/2020
13,Wuhan - China,60412.0,32.819641,2/19/2020
14,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN

In [5]:
peaked_df['location_id'] = '_' + peaked_df['location_id'].astype(str)

In [6]:
peaked_df

,location,location_id,peak day,peak_date
0,Campania - Italy,_35509.0,20.329443,4/2/2020
1,Castile and Leon - Spain,_60367.0,21.137209,4/4/2020
2,Castilla-La Mancha - Spain,_60360.0,23.081512,4/5/2020
3,Catalonia - Spain,_60368.0,25.015163,4/4/2020
4,Community of Madrid - Spain,_60361.0,26.895761,4/2/2020
5,Emilia-Romagna - Italy,_35502.0,33.783290,4/2/2020
6,King and Snohomish Counties (excluding Life Ca...,_60405.0,37.545419,4/10/2020
7,Lazio - Italy,_35506.0,25.397161,4/2/2020
8,Liguria - Italy,_35496.0,30.562541,4/5/2020
9,Lombardia - Italy,_35497.0,37.454435,3/31/2020
10,Marche - Italy,_35505.0,29.053541,4/1/2020
11,Valencian Community - Spain,_60371.0,22.124670,4/5/2020
12,Valle d'Aosta - Italy,_35495.0,16.043788,4/2/2020
13,Wuhan - China,_60412.0,32.819641,2/19/2020
14,NaN,_nan,NaN,NaN
15,NaN,_nan,NaN,NaN